**Train on whole dataset and test on test set**

In [1]:
import os
import pandas as pd 
import numpy as np

from expert_tree import get_expert_tree_results, Expert_Tree
#from wrapper import best_first_search_mg

from sklearn.metrics import confusion_matrix

In [2]:
test_set_dir = 'avon_expert_tree.csv'
data_test = pd.read_csv(test_set_dir)
#data_test.head(5)
print(data_test.shape)

(50, 14)

In [3]:

# fill 0 for missing data
for column in ['Mobility', 'ArmSwelling', 'BreastSwelling', 'Skin', 'ChestWallSwelling']:
    data_test[column].fillna(0, inplace=True)
# drop data missing important feature
data_test = data_test.dropna(subset=['TIME_LAPSE', 'LVC'])
# delete Username
data_test = data_test.drop(columns='Username')
# convert string to float
#data_test = data_test.apply(lambda x: pd.to_numeric(x, errors='coerce'))
data_test = data_test.astype(np.float64)
# drop rows containing nan
data_test = data_test.dropna()
# drop data within a 6 months
#data_test = data_test[data_test.TIME_LAPSE >=0.5]
# add log of time elapsed
#data_test['TIME_LAPSE_LOG'] = np.log(data_test['TIME_LAPSE'])

print('shape:')
print(data_test.shape)

shape:
(50, 13)

In [4]:
# generate 3 labels
expert_result, expert_labels, _ = get_expert_tree_results(data_test, False,3)
# Y_TEST is expert tree results

In [5]:
print(expert_result)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [6]:
data_test2 = pd.read_csv(test_set_dir)

In [7]:
truth_labels =data_test2['LE_stage']
temp = truth_labels
print(temp)

0     4
1     4
2     3
3     3
4     4
5     4
6     2
7     4
8     2
9     3
10    4
11    4
12    4
13    3
14    4
15    3
16    4
17    4
18    3
19    3
20    2
21    4
22    2
23    3
24    3
25    4
26    3
27    3
28    3
29    3
30    3
31    4
32    1
33    4
34    3
35    4
36    3
37    1
38    4
39    3
40    3
41    3
42    2
43    3
44    3
45    4
46    4
47    4
48    2
49    4
Name: LE_stage, dtype: int64

In [8]:
truth_labels.replace(1,0, True)
truth_labels.replace(2,1,True)
truth_labels.replace(3,2, True) #modereate and severe to tag 2 
truth_labels.replace(4,2, True)

In [9]:
truth_labels

0     2
1     2
2     2
3     2
4     2
5     2
6     1
7     2
8     1
9     2
10    2
11    2
12    2
13    2
14    2
15    2
16    2
17    2
18    2
19    2
20    1
21    2
22    1
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
31    2
32    0
33    2
34    2
35    2
36    2
37    0
38    2
39    2
40    2
41    2
42    1
43    2
44    2
45    2
46    2
47    2
48    1
49    2
Name: LE_stage, dtype: int64

EVALUATE THE RESULTS

In [10]:
from sklearn.metrics import confusion_matrix

In [11]:
t = confusion_matrix(truth_labels, expert_result, labels=[0,1,2]).ravel()
t = confusion_matrix(truth_labels, expert_result, labels=[0,1,2])
'''
print(tn, fp, fn, tp)
validation_accuracy = (tn+tp)/(tn+tp+fn+fp)
sensitivity = tp/(fn+tp)
specificty= tn/(tn+fp)
print(validation_accuracy, sensitivity,specificty )
'''
t

array([[ 2,  0,  0],
       [ 0,  1,  5],
       [ 0,  0, 42]], dtype=int64)

In [12]:
len(truth_labels) == len(expert_result)

True

In [13]:
#def tn(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 0]
#def fp(y_true, y_pred): return confusion_matrix(y_true, y_pred)[0, 1]
#def fn(y_true, y_pred): return confusion_matrix(y_true, y_pred)[1, 0]
#def tp(y_true, y_pred): return confusion_matrix(y_true, y_pred)[1, 1]

In [13]:
data_test2['clinical_label'] = truth_labels
data_test2['expert_tree_label'] = expert_labels
data_test2['expert_tree_result'] = expert_result

In [15]:
#data_test2['expert_tree_old'] = expert_tree_result2

In [14]:
data_test2

,Username,Mobility,ArmSwelling,BreastSwelling,Skin,PAS,FHT,DISCOMFORT,SYM_COUNT,TIME_LAPSE,LVC,ChestWallSwelling,fluid_total,LE_stage,clinical_label,expert_tree_label,expert_tree_result
0,C001*,4,4,4,4,4,4,4,20,3,0.540256,4,6,2,2,Severe,2
1,C002*,1,4,0,1,1,3,1,11,15,0.254824,0,4,2,2,Severe,2
2,C003,0,2,1,1,1,3,1,9,4,0.110934,0,5,2,2,Severe,2
3,C004,1,3,0,1,3,1,2,12,2,0.079574,0,4,2,2,Severe,2
4,C005,0,4,0,1,0,3,3,11,17,0.283379,3,4,2,2,Severe,2
5,C006*,1,4,0,2,3,4,2,14,19,0.359089,2,5,2,2,Severe,2
6,C007*,0,1,0,0,0,2,1,6,3,0.066416,0,2,1,1,Severe,2
7,C008,2,4,3,2,1,3,3,15,14,0.599020,3,6,2,2,Severe,2
8,C009,2,2,1,0,1,1,2,12,4,0.083401,1,5,1,1,Severe,2
9,C010*,1,2,0,0,1,1,1,10,1,0.107438,0,3,2,2,Moderate,2
10,C011,1,4,0,3,4,4,3,12,4,0.392100,0,4,2,2,Severe,2
11,C012*,2,4,0,1,2,4,2,11,4,0.151263,0,4,2,2,Severe,2
12,C013,3,4,2,1,4,4,4,16,13,0.112035,2,6,2,2,Severe,2
13,C014*,1,2,3,0,2,3,3,15,3,0.021628,3,5,2,2,Moderate,2
14,C015,1,4,4,3,0,4,2,15,2,0.251179,4,5,2,2,Severe,2
15,C016,1,4,0,0,3,2,2,12,14,0.013290,0,3,2,2,Moderate,2
16,C017*,1,4,0,2,3,3,1,18,8,0.105462,0,4,2,2,Severe,2
17,C018,2,4,4,3,2,4,3,20,3,0.675349,4,6,2,2,Severe,2
18,C019*,1,3,0,1,0,2,1,9,8,0.176085,0,3,2,2,Severe,2
19,C020*,1,2,2,0,0,1,2,9,6,0.076211,2,4,2,2,Severe,2
20,C021*,0,1,0,0,0,1,1,6,21,0.030775,0,2,1,1,Mild,1
21,C022,1,3,1,3,0,3,2,14,3,0.151152,1,5,2,2,Severe,2
22,C023,0,1,3,1,2,1,3,14,1,0.054882,2,6,1,1,Severe,2
23,C024*,1,3,0,0,2,2,3,16,9,0.090909,0,3,2,2,Severe,2
24,C025,1,3,0,1,1,2,1,9,3,0.136637,0,4,2,2,Severe,2
25,C026*,3,4,2,3,2,3,3,24,3,0.079344,2,6,2,2,Severe,2
26,C027*,1,1,2,2,2,1,2,12,1,0.074142,2,6,2,2,Severe,2
27,C028*,2,3,0,2,3,3,3,12,13,0.329514,0,4,2,2,Severe,2
28,C029*,2,3,0,2,2,3,3,13,2,0.174194,0,4,2,2,Severe,2
29,C030*,1,2,0,0,1,2,2,9,3,0.138805,0,3,2,2,Severe,2
30,C031,0,3,0,1,4,2,4,13,3,0.081494,1,5,2,2,Severe,2
31,C032,3,4,4,3,1,3,3,16,8,0.161151,0,5,2,2,Severe,2
32,C033,0,0,0,0,0,1,0,3,10,0.120739,0,1,0,0,Latent,0
33,C034,2,4,0,2,4,4,4,15,3,0.426538,0,4,2,2,Severe,2
34,C035,0,3,2,0,2,3,2,11,5,0.158979,0,4,2,2,Severe,2
35,C036,1,3,0,1,1,2,2,15,10,0.198175,0,4,2,2,Severe,2
36,C037,2,3,0,1,1,2,3,10,8,0.102868,0,4,2,2,Severe,2
37,C038,0,0,0,0,0,1,1,3,4,0.047942,0,1,0,0,Latent,0
38,C039*,2,4,2,3,3,4,4,17,2,0.944416,0,5,2,2,Severe,2
39,C040,2,3,0,2,1,2,2,13,1,0.130656,0,4,2,2,Severe,2
40,C041*,1,2,0,1,2,1,1,11,5,0.092805,2,5,2,2,Severe,2
41,C042,1,3,0,1,1,3,1,11,11,0.257115,0,4,2,2,Severe,2
42,C043,1,1,0,0,1,1,1,6,9,0.094316,0,3,1,1,Moderate,2
43,C044*,1,2,0,2,1,2,1,15,11,0.229344,0,4,2,2,Severe,2
44,C045,1,3,0,2,1,1,1,10,10,0.143223,0,4,2,2,Severe,2
45,C046,1,3,0,1,1,3,1,11,2,0.221248,0,4,2,2,Severe,2
46,C047,1,3,3,2,3,4,3,15,3,0.212047,2,6,2,2,Severe,2
47,C048,1,3,0,0,1,3,1,10,2,0.258560,0,3,2,2,Severe,2
48,C049,0,2,0,0,2,2,2,8,1,0.139049,0,3,1,1,Severe,2
49,C052,2,3,0,1,1,3,2,12,7,0.220711,0,4,2,2,Severe,2

In [15]:
result_df=data_test2[data_test2['clinical_label']!=data_test2['expert_tree_result']]

In [16]:
result_df

,Username,Mobility,ArmSwelling,BreastSwelling,Skin,PAS,FHT,DISCOMFORT,SYM_COUNT,TIME_LAPSE,LVC,ChestWallSwelling,fluid_total,LE_stage,clinical_label,expert_tree_label,expert_tree_result
6,C007*,0,1,0,0,0,2,1,6,3,0.066416,0,2,1,1,Severe,2
8,C009,2,2,1,0,1,1,2,12,4,0.083401,1,5,1,1,Severe,2
22,C023,0,1,3,1,2,1,3,14,1,0.054882,2,6,1,1,Severe,2
42,C043,1,1,0,0,1,1,1,6,9,0.094316,0,3,1,1,Moderate,2
48,C049,0,2,0,0,2,2,2,8,1,0.139049,0,3,1,1,Severe,2

In [17]:
new_column_names ={"ArmSwelling":"AS", "BreastSwelling":"BS", "DISCOMFORT":"Neuropathic", "ChestWallSwelling":"CS"}

In [18]:
result_df.drop(columns=['fluid_total', 'LE_stage']).rename(columns=new_column_names)

,Username,Mobility,AS,BS,Skin,PAS,FHT,Neuropathic,SYM_COUNT,TIME_LAPSE,LVC,CS,clinical_label,expert_tree_label,expert_tree_result
6,C007*,0,1,0,0,0,2,1,6,3,0.066416,0,1,Severe,2
8,C009,2,2,1,0,1,1,2,12,4,0.083401,1,1,Severe,2
22,C023,0,1,3,1,2,1,3,14,1,0.054882,2,1,Severe,2
42,C043,1,1,0,0,1,1,1,6,9,0.094316,0,1,Moderate,2
48,C049,0,2,0,0,2,2,2,8,1,0.139049,0,1,Severe,2